# menu
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  # About: /about

social:
  github: fuzhouxxdong

author: dxx
since: 2017

google_analytics: UA-115898584-1
google_site_verification: zdWPwymBWStc03mphQc3WEgKOEJce2_trUxr1cqFq6g

baidu_analytics: 1eb6f650adf6b4da2b2fee8afa8a1460

comments:
  disqus:
    enable: true
    shortname: dxx
    count: false
    lazyload: false
  gitment:
    enable: false
    owner: your github ID
    repo: repo
    id: your client ID
    secret: your client seret
  gitalk:
    enable: false
    owner: your github ID
    repo: repo
    id: your client ID
    secret: your client seret



